mode = "dark"
accent = "#9DFFB0"
selection = "#315C4D"
muted = "#A0B9AD"
background = "#080F0D"
dark_background = "#080F0D"
darker_background = "#080F0D"
lighter_background = "#101E19"
foreground = "#E3F2E9"
dark_foreground = "#A0B9AD"
light_foreground = "#E3F2E9"
bright_foreground = "#F4FFF8"
red = "#E58B73"
yellow = "#F2C879"
orange = "#FFAB91"
green = "#9DFFB0"
cyan = "#3FE0C5"
blue = "#89BFCB"
magenta = "#BBA9D6"
brown = "#315C4D"
bright_red = "#FFAB91"
bright_yellow = "#FFE0A0"
bright_green = "#4DFF9A"
bright_cyan = "#9AF4E1"
bright_blue = "#B4DEEA"
bright_magenta = "#D7C6EF"
