#!/usr/bin/env python3
"""A reviewable source listing: exactly one fenced block per file."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
files = []
for p in root.rglob('*'):
    if not p.is_file() or any(part in ('__pycache__','.git') for part in p.parts): continue
    if p.suffix in ('.qml','.py','.js','.lua','.conf','.toml','.theme','.jsonc') or p.name in ('qmldir','theme-hook','cedar','omarchy-shell','with-shim'):
        files.append(p)
text = '# CEDAR source files\n\nGenerated by `python3 scripts/document.py`. Paths are relative to the project and installed Quickshell directory. Generated app themes live under `themes/`.\n'
for p in sorted(files):
    lang={'.qml':'qml','.py':'python','.js':'javascript','.lua':'lua','.toml':'toml','.jsonc':'jsonc'}.get(p.suffix, 'bash' if p.name in ('theme-hook','omarchy-shell','with-shim') else 'text')
    text += '\n## '+str(p.relative_to(root))+'\n\n```'+lang+'\n'+p.read_text().rstrip()+'\n```\n'
(root/'docs/FILES.md').write_text(text)
