#!/usr/bin/env python3
"""Export app themes from Theme.qml, the sole editable color source."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
P = dict(re.findall(r'property color (\w+): (?:token\("[^"]+", )?"(#[0-9A-Fa-f]{6})"', (ROOT/'Theme.qml').read_text()))
OUT = ROOT/'themes'
OUT.mkdir(exist_ok=True)
ansi = ['background', 'ember', 'green', 'amber', 'blue', 'violet', 'teal', 'text', 'muted', 'brightEmber', 'brightGreen', 'brightAmber', 'brightBlue', 'brightViolet', 'brightTeal', 'white']


def write(name, content):
    (OUT/name).write_text(content)


kitty = {'foreground':'text', 'background':'background', 'cursor':'amber', 'cursor_text_color':'background',
         'selection_foreground':'white', 'selection_background':'border', 'active_tab_foreground':'background',
         'active_tab_background':'green', 'inactive_tab_foreground':'muted', 'inactive_tab_background':'surface',
         'tab_bar_background':'background', 'url_color':'teal', 'active_border_color':'green', 'inactive_border_color':'border'}
write('kitty.conf', '# Generated by scripts/export-themes.py\n' + '\n'.join(f'{key} {P[value]}' for key,value in kitty.items()) + '\n' +
      '\n'.join(f'color{i} {P[c]}' for i,c in enumerate(ansi)) + '''
font_family JetBrainsMono Nerd Font
font_size 11
background_opacity 0.94
cursor_shape beam
cursor_blink_interval 0
window_padding_width 12
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template " {index:02d} / {title} "
active_tab_font_style bold
inactive_tab_font_style normal
''')

btop = dict(main_bg='background', main_fg='text', title='green', hi_fg='amber', selected_bg='elevated', selected_fg='green',
            inactive_fg='muted', graph_text='text', meter_bg='border', proc_misc='teal', cpu_box='green', mem_box='teal', net_box='blue', proc_box='amber', div_line='border')
for key in ['temp', 'cpu', 'free', 'cached', 'available', 'used', 'download', 'upload', 'process']:
    for suffix,color in zip(['start','mid','end'], ['green','amber','ember'] if key in ['temp','used'] else ['teal','green','amber']):
        btop[f'{key}_{suffix}'] = color
write('btop.theme', '# Generated by scripts/export-themes.py\n' + '\n'.join(f'theme[{key}]="{P[value]}"' for key,value in btop.items()) + '\n')

colors = dict(accent='green', selection='border', muted='muted', background='background', dark_background='background', darker_background='background',
              lighter_background='surface', foreground='text', dark_foreground='muted', light_foreground='text', bright_foreground='white',
              red='ember', yellow='amber', orange='brightEmber', green='green', cyan='teal', blue='blue', magenta='violet', brown='border',
              bright_red='brightEmber', bright_yellow='brightAmber', bright_green='brightGreen', bright_cyan='brightTeal', bright_blue='brightBlue', bright_magenta='brightViolet')
write('colors.toml', 'mode = "dark"\n' + '\n'.join(f'{key} = "{P[value]}"' for key,value in colors.items()) + '\n')

lua = '-- Generated from Theme.qml. Standalone Neovim colorscheme.\nvim.cmd("highlight clear")\nvim.o.background = "dark"\nvim.g.colors_name = "cedar"\nlocal c = {\n'
lua += '\n'.join(f'  {key} = "{value}",' for key,value in P.items()) + '\n}\nlocal function hi(name, spec) vim.api.nvim_set_hl(0, name, spec) end\n'
groups = {
    'Normal':('text','background'), 'NormalFloat':('text','surface'), 'FloatBorder':('teal','surface'), 'FloatTitle':('green','surface'),
    'Comment':('muted',None), 'Constant':('amber',None), 'String':('green',None), 'Number':('amber',None), 'Boolean':('amber',None),
    'Identifier':('text',None), 'Function':('teal',None), 'Statement':('green',None), 'Keyword':('green',None), 'Operator':('teal',None),
    'PreProc':('violet',None), 'Type':('blue',None), 'Special':('amber',None), 'Delimiter':('muted',None),
    'Error':('ember','surface'), 'ErrorMsg':('ember',None), 'WarningMsg':('amber',None), 'Todo':('amber','surface'),
    'LineNr':('muted',None), 'CursorLineNr':('amber',None), 'CursorLine':(None,'surface'), 'Cursor':('background','amber'),
    'Visual':('text','border'), 'Search':('background','amber'), 'IncSearch':('background','green'),
    'StatusLine':('green','surface'), 'StatusLineNC':('muted','background'), 'WinSeparator':('border',None),
    'Pmenu':('text','surface'), 'PmenuSel':('background','green'), 'PmenuSbar':(None,'border'), 'PmenuThumb':(None,'teal'),
    'Directory':('teal',None), 'Title':('green',None), 'MatchParen':('amber','elevated'),
    'DiagnosticError':('ember',None), 'DiagnosticWarn':('amber',None), 'DiagnosticInfo':('teal',None), 'DiagnosticHint':('blue',None),
    'DiffAdd':('green','elevated'), 'DiffDelete':('ember','surface'), 'DiffChange':('amber','surface'), 'DiffText':('text','border'),
    'GitSignsAdd':('green',None), 'GitSignsChange':('amber',None), 'GitSignsDelete':('ember',None),
    '@variable':('text',None), '@function':('teal',None), '@keyword':('green',None), '@type':('blue',None), '@string':('green',None),
}
for name,(fg,bg) in groups.items():
    spec = ', '.join(x for x in [f'fg = c.{fg}' if fg else '', f'bg = c.{bg}' if bg else ''] if x)
    lua += f'hi("{name}", {{{spec}}})\n'
for i,color in enumerate(ansi): lua += f'vim.g.terminal_color_{i} = c.{color}\n'
write('cedar.lua', lua)
write('neovim.lua', '''-- Omarchy / LazyVim adapter; applied only when this theme is selected.
return {
  { "LazyVim/LazyVim", opts = { colorscheme = function()
      dofile((os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/quickshell/cedar/themes/cedar.lua")
  end } },
}
''')

# Optional, ordinary Hyprland palette snippets. No startup, bindings or distro API.
hypr = f'''-- CEDAR palette for Hyprland with Lua configuration support.
-- Optional: include from your own configuration. Does not change startup or keys.
hl.config({{
  general = {{ border_size = 1, col = {{
    active_border = {{ colors = {{ "{P['green']}", "{P['teal']}" }}, angle = 45 }},
    inactive_border = "{P['border']}",
  }} }},
  decoration = {{ rounding = 3, blur = {{ enabled = true, size = 6, passes = 2 }} }},
}})
hl.layer_rule({{ match = {{ namespace = "^cedar-.*$" }}, blur = true, ignore_alpha = 0.1 }})
'''
write('hyprland.lua', hypr)
conf = f'''# CEDAR palette for Hyprland using hyprlang configuration.
# Optional: source from your own configuration. No startup or key changes.
general {{
    border_size = 1
    col.active_border = rgb({P['green'][1:]}) rgb({P['teal'][1:]}) 45deg
    col.inactive_border = rgb({P['border'][1:]})
}}
decoration {{
    rounding = 3
    blur {{
        enabled = true
        size = 6
        passes = 2
    }}
}}
'''
write('hyprland.conf', conf)

roles = ['Forest-tinted base', 'Panel and editor surface', 'Pressed/selected surface', 'Inactive borders and selection', 'Primary cedar glow', 'Bright living green / ANSI bright green', 'Secondary teal / data links', 'Lantern amber / cursor and warnings', 'Muted ember / errors', 'Primary readable text', 'Secondary readable text / ANSI bright black', 'Cool blue / types', 'Muted violet / preprocessor', 'ANSI bright red', 'ANSI bright yellow', 'ANSI bright blue', 'ANSI bright magenta', 'ANSI bright cyan', 'Bright foreground']
rows = ['| Token | Hex | Role |','|---|---|---|']
for (name,value),role in zip(P.items(), roles): rows.append(f'| `{name}` | `{value}` | {role} |')
(ROOT/'docs/PALETTE.md').write_text('# CEDAR palette\n\n'+'\n'.join(rows)+'\n\nDerived alpha colors: transparent (0%), glass (94%), veil (88%), grid (teal at 4.5%).\n')
print('Exported kitty, btop, Neovim, colors, Hyprland and palette table.')
